cursor            #25d8ff
cursor_text_color #003641

foreground            #d8e5e9
background            #051013
selection_foreground  #0f3447
selection_background  #a9cbe3
url_color             #a9cbe3

#: black 000000 767676
color0  #091519
color8  #2b373a
#: red cc0403 f2201f
color1  #6790a2
color9  #c6d5dc
#: green 19cb00 23fd00
color2  #a9cbe3
color10 #c6e7ff
#: yellow cecb00 fffd00
color3  #a7c9f6
color11 #d2e4ff
#: blue 0d73cc 1a8fff
color4  #004e5e
color12 #25d8ff
#: magenta cb1ed1 fd28ff
color5  #294a5e
color13 #a9cbe3
#: cyan 0dcdcd 14ffff
color6  #25496e
color14 #a7c9f6
#: white dddddd ffffff
color7  #bcc9cd
color15 #d8e5e9

mark1_foreground #001f27
mark1_background #b1ecff
mark2_foreground #001e2d
mark2_background #c6e7ff
mark3_foreground #001d37
mark3_background #d2e4ff

active_tab_foreground #003641
active_tab_background #25d8ff
inactive_tab_foreground #b1ecff
inactive_tab_background #004e5e

active_border_color #25d8ff
inactive_border_color #003641
# bell_border_color #ff5a00
