cursor            #ffb0cd
cursor_text_color #640039

foreground            #f3dde3
background            #160b0f
selection_foreground  #551c36
selection_background  #ffb0cd
url_color             #ffb0cd

#: black 000000 767676
color0  #1b1014
color8  #3f3136
#: red cc0403 f2201f
color1  #194b62
color9  #45a5cf
#: green 19cb00 23fd00
color2  #ffb0cd
color10 #ffd9e4
#: yellow cecb00 fffd00
color3  #ffb59f
color11 #ffdbd1
#: blue 0d73cc 1a8fff
color4  #8b0453
color12 #ffb0cd
#: magenta cb1ed1 fd28ff
color5  #70324d
color13 #ffb0cd
#: cyan 0dcdcd 14ffff
color6  #862300
color14 #ffb59f
#: white dddddd ffffff
color7  #dcbfc8
color15 #f3dde3

mark1_foreground #3e0021
mark1_background #ffd9e4
mark2_foreground #3a0521
mark2_background #ffd9e4
mark3_foreground #3a0a00
mark3_background #ffdbd1

active_tab_foreground #640039
active_tab_background #ffb0cd
inactive_tab_foreground #ffffff
inactive_tab_background #c23b7d

active_border_color #ffb0cd
inactive_border_color #640039
# bell_border_color #ff5a00
