cursor            #88ceff
cursor_text_color #00344d

foreground            #dbe3ed
background            #070f15
selection_foreground  #1d314b
selection_background  #b4c8e9
url_color             #b4c8e9

#: black 000000 767676
color0  #0c141b
color8  #2d363d
#: red cc0403 f2201f
color1  #154866
color9  #3d9dd7
#: green 19cb00 23fd00
color2  #b4c8e9
color10 #d4e3ff
#: yellow cecb00 fffd00
color3  #b9c4fa
color11 #dde1ff
#: blue 0d73cc 1a8fff
color4  #004c6e
color12 #88ceff
#: magenta cb1ed1 fd28ff
color5  #344863
color13 #b4c8e9
#: cyan 0dcdcd 14ffff
color6  #394472
color14 #b9c4fa
#: white dddddd ffffff
color7  #bfc8d0
color15 #dbe3ed

mark1_foreground #001e2f
mark1_background #c8e6ff
mark2_foreground #051c35
mark2_background #d4e3ff
mark3_foreground #0b1844
mark3_background #dde1ff

active_tab_foreground #00344d
active_tab_background #88ceff
inactive_tab_foreground #c8e6ff
inactive_tab_background #004c6e

active_border_color #88ceff
inactive_border_color #00344d
# bell_border_color #ff5a00
