cursor            #ffb784
cursor_text_color #4f2500

foreground            #f7dece
background            #170c05
selection_foreground  #452b07
selection_background  #eabf8f
url_color             #eabf8f

#: black 000000 767676
color0  #1d1108
color8  #413227
#: red cc0403 f2201f
color1  #83470c
color9  #ed943b
#: green 19cb00 23fd00
color2  #eabf8f
color10 #ffddb9
#: yellow cecb00 fffd00
color3  #e7c177
color11 #ffdea2
#: blue 0d73cc 1a8fff
color4  #713700
color12 #ffb784
#: magenta cb1ed1 fd28ff
color5  #5e411c
color13 #eabf8f
#: cyan 0dcdcd 14ffff
color6  #5c4301
color14 #e7c177
#: white dddddd ffffff
color7  #dac2b3
color15 #f7dece

mark1_foreground #301400
mark1_background #ffdcc5
mark2_foreground #2b1700
mark2_background #ffddb9
mark3_foreground #261900
mark3_background #ffdea2

active_tab_foreground #4f2500
active_tab_background #ffb784
inactive_tab_foreground #ffdcc5
inactive_tab_background #713700

active_border_color #ffb784
inactive_border_color #4f2500
# bell_border_color #ff5a00
