$image = /home/umar/Pictures/Wallpapers/PC_wallpapers/cat4.png

$background = rgba(1c1014ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(3b2c31ff)

$inverse_primary = rgba(b8006eff)

$inverse_surface = rgba(f5dce3ff)

$on_background = rgba(f5dce3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(640039ff)

$on_primary_container = rgba(ffd9e4ff)

$on_primary_fixed = rgba(3e0021ff)

$on_primary_fixed_variant = rgba(8c0053ff)

$on_secondary = rgba(4b252cff)

$on_secondary_container = rgba(ffd9deff)

$on_secondary_fixed = rgba(321018ff)

$on_secondary_fixed_variant = rgba(653b42ff)

$on_surface = rgba(f5dce3ff)

$on_surface_variant = rgba(d8c1c7ff)

$on_tertiary = rgba(53201fff)

$on_tertiary_container = rgba(ffdad7ff)

$on_tertiary_fixed = rgba(380b0cff)

$on_tertiary_fixed_variant = rgba(6f3634ff)

$outline = rgba(a08b91ff)

$outline_variant = rgba(534248ff)

$primary = rgba(ffb0cdff)

$primary_container = rgba(8c0053ff)

$primary_fixed = rgba(ffd9e4ff)

$primary_fixed_dim = rgba(ffb0cdff)

$scrim = rgba(000000ff)

$secondary = rgba(f2b7c0ff)

$secondary_container = rgba(653b42ff)

$secondary_fixed = rgba(ffd9deff)

$secondary_fixed_dim = rgba(f2b7c0ff)

$shadow = rgba(000000ff)

$source_color = rgba(c23b7dff)

$surface = rgba(1c1014ff)

$surface_bright = rgba(45353aff)

$surface_container = rgba(291c21ff)

$surface_container_high = rgba(35262bff)

$surface_container_highest = rgba(403136ff)

$surface_container_low = rgba(25181dff)

$surface_container_lowest = rgba(170b0fff)

$surface_dim = rgba(1c1014ff)

$surface_tint = rgba(ffb0cdff)

$surface_variant = rgba(534248ff)

$tertiary = rgba(ffb3afff)

$tertiary_container = rgba(6f3634ff)

$tertiary_fixed = rgba(ffdad7ff)

$tertiary_fixed_dim = rgba(ffb3afff)

