$image = /home/umar/Pictures/Wallpapers/PC_wallpapers/cat01.jpg

$background = rgba(091519ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(273236ff)

$inverse_primary = rgba(00677cff)

$inverse_surface = rgba(d8e5e9ff)

$on_background = rgba(d8e5e9ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003641ff)

$on_primary_container = rgba(b1ecffff)

$on_primary_fixed = rgba(001f27ff)

$on_primary_fixed_variant = rgba(004e5eff)

$on_secondary = rgba(0f3447ff)

$on_secondary_container = rgba(c6e7ffff)

$on_secondary_fixed = rgba(001e2dff)

$on_secondary_fixed_variant = rgba(294a5eff)

$on_surface = rgba(d8e5e9ff)

$on_surface_variant = rgba(bcc9cdff)

$on_tertiary = rgba(063257ff)

$on_tertiary_container = rgba(d2e4ffff)

$on_tertiary_fixed = rgba(001d37ff)

$on_tertiary_fixed_variant = rgba(25496eff)

$outline = rgba(879397ff)

$outline_variant = rgba(3d494dff)

$primary = rgba(25d8ffff)

$primary_container = rgba(004e5eff)

$primary_fixed = rgba(b1ecffff)

$primary_fixed_dim = rgba(25d8ffff)

$scrim = rgba(000000ff)

$secondary = rgba(a9cbe3ff)

$secondary_container = rgba(294a5eff)

$secondary_fixed = rgba(c6e7ffff)

$secondary_fixed_dim = rgba(a9cbe3ff)

$shadow = rgba(000000ff)

$source_color = rgba(566165ff)

$surface = rgba(091519ff)

$surface_bright = rgba(2f3b3fff)

$surface_container = rgba(162125ff)

$surface_container_high = rgba(202c30ff)

$surface_container_highest = rgba(2b373aff)

$surface_container_low = rgba(121d21ff)

$surface_container_lowest = rgba(051013ff)

$surface_dim = rgba(091519ff)

$surface_tint = rgba(25d8ffff)

$surface_variant = rgba(3d494dff)

$tertiary = rgba(a7c9f6ff)

$tertiary_container = rgba(25496eff)

$tertiary_fixed = rgba(d2e4ffff)

$tertiary_fixed_dim = rgba(a7c9f6ff)

