$image = /home/umar/Pictures/Wallpapers/PC_wallpapers/cat4.png

$background = rgba(1b1014ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(3a2d31ff)

$inverse_primary = rgba(ab286bff)

$inverse_surface = rgba(f3dde3ff)

$on_background = rgba(f3dde3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(640039ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(3e0021ff)

$on_primary_fixed_variant = rgba(8b0453ff)

$on_secondary = rgba(551c36ff)

$on_secondary_container = rgba(ffd5e2ff)

$on_secondary_fixed = rgba(3a0521ff)

$on_secondary_fixed_variant = rgba(70324dff)

$on_surface = rgba(f3dde3ff)

$on_surface_variant = rgba(dcbfc8ff)

$on_tertiary = rgba(5f1600ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(3a0a00ff)

$on_tertiary_fixed_variant = rgba(862300ff)

$outline = rgba(a48a92ff)

$outline_variant = rgba(564148ff)

$primary = rgba(ffb0cdff)

$primary_container = rgba(c23b7dff)

$primary_fixed = rgba(ffd9e4ff)

$primary_fixed_dim = rgba(ffb0cdff)

$scrim = rgba(000000ff)

$secondary = rgba(ffb0cdff)

$secondary_container = rgba(70324dff)

$secondary_fixed = rgba(ffd9e4ff)

$secondary_fixed_dim = rgba(ffb0cdff)

$shadow = rgba(000000ff)

$source_color = rgba(c23b7dff)

$surface = rgba(1b1014ff)

$surface_bright = rgba(43363aff)

$surface_container = rgba(281c20ff)

$surface_container_high = rgba(33272bff)

$surface_container_highest = rgba(3f3136ff)

$surface_container_low = rgba(24181cff)

$surface_container_lowest = rgba(160b0fff)

$surface_dim = rgba(1b1014ff)

$surface_tint = rgba(ffb0cdff)

$surface_variant = rgba(564148ff)

$tertiary = rgba(ffb59fff)

$tertiary_container = rgba(c5441aff)

$tertiary_fixed = rgba(ffdbd1ff)

$tertiary_fixed_dim = rgba(ffb59fff)

